name: Deploy Backend API to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'ScheduleDay/ScheduleDay/**'
      - 'ScheduleDay/ScheduleDay.Shared/**'
      - '.github/workflows/api-deploy.yml'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ScheduleDay/ScheduleDay.sln
      
    - name: Build
      run: dotnet build ScheduleDay/ScheduleDay.sln --configuration Release --no-restore
      
    - name: Publish API
      run: dotnet publish ScheduleDay/ScheduleDay/ScheduleDay.csproj -c Release -o ${{github.workspace}}/publish-api
      
    - name: Deploy to Azure Web App (API)
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'scheduledayapp-api'  # Name of your App Service for API
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_API_PUBLISH_PROFILE }}
        package: ${{github.workspace}}/publish-api